export const perguntas = [
  { id: 0, grupoId: 0, text: "O que é conectivismo?", virado: false },
  {
    id: 1,
    grupoId: 0,
    text: "Uma teoria de aprendizagem que enfatiza redes e tecnologia.",
    virado: false,
  },
  {
    id: 2,
    grupoId: 1,
    text: "Como o conectivismo vê o aprendizado?",
    virado: false,
  },
  {
    id: 3,
    grupoId: 1,
    text: "Como um processo de conectar informações e ideias.",
    virado: false,
  },
  {
    id: 4,
    grupoId: 2,
    text: "Qual o papel da tecnologia no conectivismo?",
    virado: false,
  },
  {
    id: 5,
    grupoId: 2,
    text: "Facilitar conexões e acesso ao conhecimento.",
    virado: false,
  },
  {
    id: 6,
    grupoId: 3,
    text: "Onde o aprendizado pode residir, segundo o conectivismo?",
    virado: false,
  },
  {
    id: 7,
    grupoId: 3,
    text: "Em pessoas, dispositivos e redes.",
    virado: false,
  },
  {
    id: 8,
    grupoId: 4,
    text: "O que é 'meia-vida do conhecimento'?",
    virado: false,
  },
  {
    id: 9,
    grupoId: 4,
    text: "O tempo até o conhecimento se tornar obsoleto.",
    virado: false,
  },
  {
    id: 10,
    grupoId: 5,
    text: "Por que conexões são importantes?",
    virado: false,
  },
  {
    id: 11,
    grupoId: 5,
    text: "Elas permitem acesso contínuo a novos conhecimentos.",
    virado: false,
  },
  {
    id: 12,
    grupoId: 6,
    text: "Qual é um princípio-chave do conectivismo?",
    virado: false,
  },
  {
    id: 13,
    grupoId: 6,
    text: "A diversidade de opiniões enriquece o aprendizado.",
    virado: false,
  },
  {
    id: 14,
    grupoId: 7,
    text: "Como o conectivismo aborda a inovação?",
    virado: false,
  },
  {
    id: 15,
    grupoId: 7,
    text: "Ao conectar ideias e áreas diferentes para gerar novidades.",
    virado: false,
  },
  {
    id: 16,
    grupoId: 8,
    text: "O que é educação a distância (EaD)?",
    virado: false,
  },
  {
    id: 17,
    grupoId: 8,
    text: "Uma forma de ensino mediada por tecnologias, acessível remotamente.",
    virado: false,
  },
  {
    id: 18,
    grupoId: 9,
    text: "Como a EaD promove flexibilidade?",
    virado: false,
  },
  {
    id: 19,
    grupoId: 9,
    text: "Permite que alunos escolham quando e onde estudar.",
    virado: false,
  },
  {
    id: 20,
    grupoId: 10,
    text: "Qual é o papel do professor na EaD?",
    virado: false,
  },
  {
    id: 21,
    grupoId: 10,
    text: "Facilitar, guiar e apoiar os alunos no aprendizado remoto.",
    virado: false,
  },
  {
    id: 22,
    grupoId: 11,
    text: "O que é autoaprendizado na EaD?",
    virado: false,
  },
  {
    id: 23,
    grupoId: 11,
    text: "Quando o aluno é responsável pelo ritmo e planejamento do estudo.",
    virado: false,
  },
  {
    id: 24,
    grupoId: 12,
    text: "Como a tecnologia mudou a educação?",
    virado: false,
  },
  {
    id: 25,
    grupoId: 12,
    text: "Ampliou o acesso e permitiu novas formas de interação.",
    virado: false,
  },
  {
    id: 26,
    grupoId: 13,
    text: "Como a EaD ajuda a superar barreiras geográficas?",
    virado: false,
  },
  {
    id: 27,
    grupoId: 13,
    text: "Oferecendo acesso remoto a conteúdos e especialistas.",
    virado: false,
  },
  {
    id: 28,
    grupoId: 14,
    text: "O que significa 'conhecer onde encontrar'?",
    virado: false,
  },
  {
    id: 29,
    grupoId: 14,
    text: "A habilidade de saber onde acessar o conhecimento necessário.",
    virado: false,
  },
  {
    id: 30,
    grupoId: 15,
    text: "Qual é o papel da colaboração na EaD?",
    virado: false,
  },
  {
    id: 31,
    grupoId: 15,
    text: "Estimular o aprendizado por meio de interações com colegas e professores.",
    virado: false,
  },
  {
    id: 32,
    grupoId: 16,
    text: "Como o conectivismo redefine o aprendizado?",
    virado: false,
  },
  {
    id: 33,
    grupoId: 16,
    text: "Enfatizando redes e conexões como centrais no processo educacional.",
    virado: false,
  },
  {
    id: 34,
    grupoId: 17,
    text: "Como a EaD se adapta às mudanças rápidas?",
    virado: false,
  },
  {
    id: 35,
    grupoId: 17,
    text: "Atualizando conteúdos e adotando tecnologias emergentes.",
    virado: false,
  },
  {
    id: 36,
    grupoId: 18,
    text: "Por que auto-organização é importante no conectivismo?",
    virado: false,
  },
  {
    id: 37,
    grupoId: 18,
    text: "Para adaptar-se e criar significado em ambientes complexos.",
    virado: false,
  },
  {
    id: 38,
    grupoId: 19,
    text: "O que significa 'aprendizagem contínua'?",
    virado: false,
  },
  {
    id: 39,
    grupoId: 19,
    text: "É o aprendizado que ocorre ao longo da vida, integrando-se ao cotidiano.",
    virado: false,
  },
  {
    id: 40,
    grupoId: 20,
    text: "Como o conectivismo vê redes sociais?",
    virado: false,
  },
  {
    id: 41,
    grupoId: 20,
    text: "Como facilitadoras do aprendizado por meio da troca de conhecimentos.",
    virado: false,
  },
  {
    id: 42,
    grupoId: 21,
    text: "Como a EaD beneficia alunos em áreas remotas?",
    virado: false,
  },
  {
    id: 43,
    grupoId: 21,
    text: "Ao oferecer acesso a cursos e especialistas antes indisponíveis.",
    virado: false,
  },
  {
    id: 44,
    grupoId: 22,
    text: "Qual a importância da diversidade na EaD?",
    virado: false,
  },
  {
    id: 45,
    grupoId: 22,
    text: "Enriquece o aprendizado com múltiplas perspectivas culturais.",
    virado: false,
  },
  {
    id: 46,
    grupoId: 23,
    text: "Como o conectivismo lida com a sobrecarga de informações?",
    virado: false,
  },
  {
    id: 47,
    grupoId: 23,
    text: "Ao priorizar conexões relevantes e úteis para o aprendizado.",
    virado: false,
  },
];
